import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Music, Megaphone, Headphones, Sliders, Mic2, ArrowRight, Clock, ScrollText, ShieldCheck, Coins, Video, ChevronRight } from 'lucide-react';
import { Helmet } from 'react-helmet-async';
import { Link } from 'react-router-dom';
import SEO from '../components/SEO';

interface Service {
    id: string;
    name: string;
    tagline: string;
    icon: React.ElementType;
    comingSoon?: boolean;
    description: string;
    features?: string[];
    link?: string;
    linkText?: string;
}

const services: Service[] = [
    {
        id: 'records',
        name: 'WBBT Records',
        tagline: 'Music Distribution',
        icon: Music,
        description: `Important: We are not just a distributor — we are a record label. When you sign with WBBT Records, you become part of a family that genuinely invests in your success.

Your gateway to the world's biggest streaming platforms. WBBT Records delivers your music to over 150+ digital stores and streaming services including Spotify, Apple Music, Amazon Music, Deezer, Tidal, YouTube Music, and countless others across every continent.

We don't just distribute — we optimize. Our team ensures your releases are properly formatted, tagged with rich metadata, and strategically scheduled for maximum impact. With our advanced analytics dashboard, you'll track your streams, revenue, and audience demographics in real-time.`,
        features: ['150+ Streaming Platforms', 'Global Distribution', 'Royalty Collection', 'Analytics Dashboard', 'Release Scheduling', 'Metadata Optimization'],
        link: '/submit',
        linkText: 'Submit Your Music'
    },
    {
        id: 'publishing',
        name: 'Music Publishing',
        tagline: 'Royalties & Licensing',
        icon: ScrollText,
        description: `Your music generates revenue in ways you might not even realize. WBBT Publishing ensures you collect every cent your composition earns globally. We handle the complex administration of your mechanical and performance rights.

We register your songs with collection societies worldwide (like ASCAP, BMI, PRS, GEMA) to track when your music is played on radio, TV, live venues, or streaming platforms. We also actively pitch your catalog for sync licensing opportunities in film, TV, ads, and video games.`,
        features: ['Global Royalty Collection', 'Sync Licensing Pitching', 'PRO Registration', 'Performance Royalties', 'Mechanical Royalties', 'Neighboring Rights'],
        link: '/submit',
        linkText: 'Sign Up for Publishing'
    },
    {
        id: 'pr',
        name: 'WBBT PR',
        tagline: 'Music Promotion',
        icon: Megaphone,
        description: `In today's saturated music landscape, great music alone isn't enough. You need a story. You need visibility. You need WBBT PR. Our dedicated team of music marketing specialists works tirelessly to amplify your presence across every corner of the industry.

From securing coveted playlist placements on Spotify's editorial collections to landing features in major music publications, we craft compelling narratives that resonate. Our comprehensive PR packages include strategic social media campaigns designed to grow your following organically.`,
        features: ['Playlist Pitching', 'Press Coverage', 'Social Media Campaigns', 'Influencer Partnerships', 'Radio Plugging', 'Brand Collaborations'],
        link: '/submit',
        linkText: 'Get in Touch'
    },
    {
        id: 'video',
        name: 'Video Publishing',
        tagline: 'Distribution & Monetization',
        icon: Video,
        description: `Visuals are just as important as audio. WBBT Video Publishing distributes your music videos to major platforms like Vevo, Apple Music, Tidal, and Amazon Video, ensuring premium placement and monetization.

We manage your official artist channel on YouTube, optimizing your content for the algorithm to drive subscribers and views. We also handle rights management for your video content, ensuring you earn revenue whenever your visual assets are viewed or used.`,
        features: ['Vevo Channel Creation', 'Apple Music Videos', 'YouTube Optimization', 'Video Monetization', 'Premium Distribution', 'Rights Management']
    },
    {
        id: 'rights',
        name: 'Rights Collection',
        tagline: 'Neighboring & Digital',
        icon: Coins,
        description: `Beyond standard songwriting royalties, there's a whole world of "neighboring rights" and digital performance royalties generated by the sound recording itself. We collect these for you directly.
        
We register your tracks with SoundExchange and other neighboring rights organizations to collect royalties for non-interactive streams (like Pandora or SiriusXM) and satellite radio plays.`,
        features: ['SoundExchange Registration', 'Satellite Radio Collection', 'Non-Interactive Streaming', 'Royalty Auditing', 'Global Neighboring Rights']
    },
    {
        id: 'copyright',
        name: 'Copyright Protection',
        tagline: 'Content ID & Rights',
        icon: ShieldCheck,
        description: `Protect your intellectual property in the digital age. Our advanced Content ID systems scan the internet to find unauthorized uses of your music across major platforms like YouTube, Facebook, Instagram, and TikTok.

When we find your music being used, we claim it on your behalf. You can choose to monetize that content (turning piracy into profit) or issue takedowns.`,
        features: ['YouTube Content ID', 'Facebook Rights Manager', 'TikTok Audio Protection', 'Piracy Monitoring', 'Takedown Services', 'Legal Support']
    },
    {
        id: 'aura',
        name: 'WBBT Aura',
        tagline: 'Spatial Audio',
        icon: Headphones,
        comingSoon: true,
        description: `Experience sound in three dimensions. WBBT Aura is our proprietary spatial audio engine that transforms traditional stereo mixes into immersive, multi-dimensional soundscapes.

Imagine placing instruments and vocals anywhere in a 360-degree sphere around the listener — above, below, behind, in front. Sound that doesn't just play; it surrounds and envelops.`,
        features: ['3D Sound Positioning', '360° Immersive Audio', 'Headphone Optimization', 'Multi-Channel Export', 'Real-time Preview']
    },
    {
        id: 'fx',
        name: 'WBBT FX',
        tagline: 'Audio Plugins',
        icon: Sliders,
        comingSoon: true,
        description: `Studio-grade audio processing tools designed for the modern producer. The WBBT FX suite delivers professional results with intuitive, beautifully designed interfaces.

Our crystal-clear EQ algorithms let you sculpt frequencies with surgical precision. Our reverb engines create spaces from intimate rooms to infinite halls.`,
        features: ['WBBT EQ Pro', 'WBBT Reverb', 'WBBT Compressor', 'WBBT Saturator', 'Low CPU Usage', 'Modern UI']
    },
    {
        id: 'wavr',
        name: 'WBBT Wavr',
        tagline: 'AI Voice Synthesis',
        icon: Mic2,
        comingSoon: true,
        description: `The future of vocal production is here. WBBT Wavr harnesses the power of advanced neural networks to generate hyper-realistic vocal performances on demand.

Need backing vocals? Generate lush harmonies with a few clicks. Want to experiment with different vocal styles? Switch between our library of AI voices instantly.`,
        features: ['Neural Voice Synthesis', 'Custom Voice Training', 'Harmony Generation', 'AI Voice Library', 'Real-time Processing']
    }
];

const ServicesPage = () => {
    const [activeServiceId, setActiveServiceId] = useState<string>(services[0].id);

    const activeService = services.find(s => s.id === activeServiceId) || services[0];

    return (
        <>
            <SEO
                title="Services | WBBT - Music Distribution, PR & Audio Technology"
                description="Discover WBBT's comprehensive music services: global distribution, professional PR, and upcoming audio technologies."
                keywords="Music Services, Music Distribution, Music PR, Audio Plugins, Record Label Services, WBBT Records"
            />

            <div className="pt-32 pb-20 px-6 md:px-12 max-w-[1600px] mx-auto min-h-screen">
                <div className="flex flex-col lg:flex-row gap-12 lg:gap-24">
                    {/* LEFT COLUMN: Service List */}
                    <div className="lg:w-1/3 flex flex-col gap-2">
                        <motion.div
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                            className="mb-8 lg:mb-12"
                        >
                            <h1 className="font-display text-5xl md:text-7xl font-black text-white mb-4">
                                Our<br />Services
                            </h1>
                            <div className="h-1 w-24 bg-purple-600 rounded-full" />
                        </motion.div>

                        <div className="flex flex-col gap-2">
                            {services.map((service) => (
                                <div key={service.id} className="flex flex-col">
                                    {/* List Item Button */}
                                    <button
                                        onClick={() => setActiveServiceId(service.id)}
                                        className={`group relative p-6 text-left rounded-2xl transition-all duration-300 border ${activeServiceId === service.id ? 'bg-white/10 border-white/20' : 'bg-transparent border-transparent hover:bg-white/5'}`}
                                    >
                                        <div className="flex items-center justify-between">
                                            <div>
                                                <h3 className={`font-display text-xl font-bold transition-colors ${activeServiceId === service.id ? 'text-white' : 'text-gray-500 group-hover:text-gray-300'}`}>
                                                    {service.name}
                                                </h3>
                                                <p className={`text-xs uppercase tracking-widest transition-colors ${activeServiceId === service.id ? 'text-purple-400' : 'text-gray-600'}`}>
                                                    {service.tagline}
                                                </p>
                                            </div>
                                            <div className="flex items-center">
                                                {/* Desktop Indicator - Hidden on Mobile */}
                                                {activeServiceId === service.id && (
                                                    <motion.div layoutId="activeIndicator" className="hidden lg:block">
                                                        <ChevronRight className="text-purple-400" size={20} />
                                                    </motion.div>
                                                )}

                                                {/* Mobile Chevron - Rotates when active */}
                                                <ChevronRight className={`lg:hidden text-gray-500 transition-transform duration-300 ${activeServiceId === service.id ? 'rotate-90 text-purple-400' : ''}`} size={20} />
                                            </div>
                                        </div>
                                        {service.comingSoon && (
                                            <div className="absolute top-6 right-12 lg:right-12">
                                                <Clock className="w-4 h-4 text-yellow-500 opacity-50" />
                                            </div>
                                        )}
                                    </button>

                                    {/* MOBILE CONTENT: Accordion Expansion */}
                                    {/* This only shows on mobile (lg:hidden) and when active */}
                                    <div className="lg:hidden overflow-hidden">
                                        <AnimatePresence>
                                            {activeServiceId === service.id && (
                                                <motion.div
                                                    initial={{ height: 0, opacity: 0 }}
                                                    animate={{ height: 'auto', opacity: 1 }}
                                                    exit={{ height: 0, opacity: 0 }}
                                                    transition={{ duration: 0.3 }}
                                                >
                                                    <div className="p-6 pt-0 border-l border-white/10 ml-6 my-4">
                                                        <div className="prose prose-invert prose-sm max-w-none mb-6">
                                                            {service.description.split('\n\n').map((paragraph, i) => (
                                                                <p key={i} className="text-gray-300 leading-relaxed mb-4">
                                                                    {paragraph}
                                                                </p>
                                                            ))}
                                                        </div>
                                                        {service.features && (
                                                            <div className="mb-6">
                                                                <h4 className="text-xs font-bold text-gray-500 uppercase tracking-widest mb-3">Includes</h4>
                                                                <div className="flex flex-wrap gap-2">
                                                                    {service.features.map((feature) => (
                                                                        <span key={feature} className="px-3 py-1 bg-white/5 border border-white/10 rounded-full text-xs text-gray-300">
                                                                            {feature}
                                                                        </span>
                                                                    ))}
                                                                </div>
                                                            </div>
                                                        )}
                                                        {service.link && (
                                                            <Link
                                                                to={service.link}
                                                                className="inline-flex items-center gap-2 text-purple-400 font-bold uppercase tracking-wider text-sm hover:text-white transition-colors"
                                                            >
                                                                {service.linkText}
                                                                <ArrowRight className="w-4 h-4" />
                                                            </Link>
                                                        )}
                                                    </div>
                                                </motion.div>
                                            )}
                                        </AnimatePresence>
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>

                    {/* RIGHT COLUMN: Active Service Detail (Sticky) - DESKTOP ONLY */}
                    <div className="hidden lg:block lg:w-2/3 lg:sticky lg:top-32 lg:h-[80vh]">
                        <AnimatePresence mode="wait">
                            <motion.div
                                key={activeService.id}
                                initial={{ opacity: 0, x: 20 }}
                                animate={{ opacity: 1, x: 0 }}
                                exit={{ opacity: 0, x: -20 }}
                                transition={{ duration: 0.3 }}
                                className="h-full bg-gradient-to-br from-white/5 to-transparent border border-white/10 rounded-3xl backdrop-blur-sm relative overflow-hidden"
                            >
                                {/* Background Icon Watermark */}
                                <activeService.icon className="absolute -right-12 -bottom-12 w-96 h-96 text-white/5 pointer-events-none" />

                                {/* Scrollable Content Area */}
                                <div className="h-full overflow-y-auto custom-scrollbar relative z-10">
                                    <div className="min-h-full p-8 md:p-12 flex flex-col justify-center">
                                        <div className="w-16 h-16 bg-purple-600/20 border border-purple-500/30 rounded-2xl flex items-center justify-center mb-8">
                                            <activeService.icon className="w-8 h-8 text-purple-400" />
                                        </div>

                                        <div className="flex items-center gap-4 mb-2">
                                            <h2 className="font-display text-4xl md:text-6xl font-black text-white">
                                                {activeService.name}
                                            </h2>
                                            {activeService.comingSoon && (
                                                <span className="px-3 py-1 bg-yellow-500/20 text-yellow-500 text-xs font-bold uppercase rounded-full border border-yellow-500/20">
                                                    Coming Soon
                                                </span>
                                            )}
                                        </div>

                                        <p className="text-purple-400 text-sm md:text-base uppercase tracking-widest mb-8">
                                            {activeService.tagline}
                                        </p>

                                        <div className="prose prose-invert max-w-none mb-10">
                                            {activeService.description.split('\n\n').map((paragraph, i) => (
                                                <p key={i} className="text-gray-300 text-lg leading-relaxed mb-4">
                                                    {paragraph}
                                                </p>
                                            ))}
                                        </div>

                                        {activeService.features && (
                                            <div className="mb-12">
                                                <h4 className="text-sm font-bold text-gray-400 uppercase tracking-widest mb-4">Includes</h4>
                                                <div className="flex flex-wrap gap-3">
                                                    {activeService.features.map((feature) => (
                                                        <span key={feature} className="px-4 py-2 bg-white/5 border border-white/10 rounded-full text-sm text-gray-300 hover:bg-white/10 transition-colors">
                                                            {feature}
                                                        </span>
                                                    ))}
                                                </div>
                                            </div>
                                        )}

                                        {activeService.link && (
                                            <div>
                                                <Link
                                                    to={activeService.link}
                                                    className="inline-flex items-center gap-3 px-8 py-4 bg-white text-black font-bold uppercase tracking-widest rounded-full hover:bg-purple-400 transition-colors"
                                                >
                                                    {activeService.linkText}
                                                    <ArrowRight className="w-5 h-5" />
                                                </Link>
                                            </div>
                                        )}
                                    </div>
                                </div>
                            </motion.div>
                        </AnimatePresence>
                    </div>
                </div>
            </div>
        </>
    );
};

export default ServicesPage;
